# fly.toml app configuration file generated for management-dashboard-little-frost-5784 on 2023-12-15T18:28:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "management-dashboard-little-frost-5784"
primary_region = "mia"

[env]
  APP_PORT=80
  HOST="management-dashboard-little-frost-5784.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
